// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv6Riv5KSfTl6D4XkTKk2UoxebP31N7Ic',
    appId: '1:516978614827:web:9c5b0535ab5756eab3806e',
    messagingSenderId: '516978614827',
    projectId: 'flutter-chat-app-bf70a',
    authDomain: 'flutter-chat-app-bf70a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bf70a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ciTrUDh-4TI60_uzYFqo33L2M_iRPhg',
    appId: '1:516978614827:android:d08a595c71692e9ab3806e',
    messagingSenderId: '516978614827',
    projectId: 'flutter-chat-app-bf70a',
    storageBucket: 'flutter-chat-app-bf70a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDTWfOoz_XK6-aXxzUVHNsKej8sV-z9hU',
    appId: '1:516978614827:ios:58edceac138e5c80b3806e',
    messagingSenderId: '516978614827',
    projectId: 'flutter-chat-app-bf70a',
    storageBucket: 'flutter-chat-app-bf70a.appspot.com',
    iosClientId: '516978614827-ibsqod1ent06ha7tfiuf35k5ut1tmoso.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDTWfOoz_XK6-aXxzUVHNsKej8sV-z9hU',
    appId: '1:516978614827:ios:6aff9dbc4fd8e679b3806e',
    messagingSenderId: '516978614827',
    projectId: 'flutter-chat-app-bf70a',
    storageBucket: 'flutter-chat-app-bf70a.appspot.com',
    iosClientId: '516978614827-mpv8mu1epcj6rptma7umfpckv9s0pec1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
